### PR TITLE
fix: allow globalThis fallback for this

### LINKED ISSUE #3: Crashes when 'this' scope is undefined (ESM)
👋 Hi, thanks for making this great project! I use it as the Konami Code detector in all of emojiblast.dev's projects.

When trying to use it in a project built with Nuxt, these crashes are happening:

```plaintext
Uncaught TypeError: Cannot read properties of undefined (reading 'KonamiCode')
    at konami-code.js?v=c042648a:14:29
    at konami-code.js?v=c042648a:44:2
```

At runtime, the main function's `root` is `undefined` because` this` is undefined ([StackOverflow ESM `this` question](https://stackoverflow.com/questions/48670599/why-is-this-undefined-in-script-type-module) -> [ESM `this` spec](https://262.ecma-international.org/8.0/#sec-module-environment-records-getthisbinding).

Reproduction: https://github.com/JoshuaKGoldberg/repros/tree/repro-konami-code-js-esm-nuxt

Would you be open to a PR that defaults `root` to `globalThis` if `this` isn't defined?

I sent #4 as a reference.

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
Fixes #3.

If `this` is not defined, I believe that means we can be sure we're in an environment with `globalThis` defined.

### CODE REVIEW

File: src/konami-code.js [hunk 1]
```diff
@@ -41,7 +41,7 @@
     if (typeof module === "object" && module.exports) {
         module.exports = factory;
     }
-}(this, function callee(options) {
+}(this ?? globalThis, function callee(options) {
```
Comment (JoshuaKGoldberg) [inline src/konami-code.js]: Actually, I don't know that `konami-code-js` doesn't still explicitly support very old runtimes, so:

```suggestion
}(this || globalThis, function callee(options) {
```

**Comment by MachinisteWeb** [comment]
Good to me! Good point!

**Comment by JoshuaKGoldberg** [comment]
Awesome, thanks for the quick turnaround!
